name: Deploy android app
on:
  push:
    branches:
      - master

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: Build Android Staging
        working-directory: ./android
        run: ./gradlew assembleStaging

      - name: Distribute to DeployGate
        working-directory: ./android
        run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "file=@app/build/outputs/apk/staging/app-staging.apk" \
            -F "message=$(git rev-parse --short HEAD)" \
            -F "distribution_name=FasciaStg" \
            -v "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
